name: Build

on: [push, pull_request]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Lint
      uses: actions/setup-node@v2
      with:
        node-version: lts/*
    - run: npm ci
    - run: npm run lint

  publish:

    runs-on: ubuntu-latest

    needs: [lint, test]

    steps:
    - uses: actions/checkout@v2
    - name: Publish
      uses: actions/setup-node@v2
      with:
        node-version: lts/*
        registry-url: https://registry.npmjs.org/
    - run: npm ci
    - run: npm run build
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      if: contains(github.ref, 'tags/v')
